## Make sure to assume readonly role in dev account before running these tasks

require 'bundler/setup'
Bundler.require(:default)

ENV['AWS_REGION'] ||= 'eu-west-1'
def get_ssm_param_value(key)
  @ssm ||= Aws::SSM::Client.new
  @ssm.get_parameters(names: [key], with_decryption: true).parameters[0].value
end

namespace :test do
  task :configure do
    ENV['SELENIUM_BACKEND'] = 'aws'
    # next 2 are required for SELENIUM_BACKEND=aws
    ENV['MARIONETTES_USER'] = 'showcar'
    ENV['MARIONETTES_PASSWORD'] = get_ssm_param_value('showcar-marionettes-password')

    ENV['FORK'] = '4'
    ENV['RSPEC_RETRY_RETRY_COUNT'] = '3'
    ENV['TOGURU_TOGGLES'] = ["sc_develop=true"].unshift(ENV['TOGURU_TOGGLES']).compact.join('|')
  end

  desc 'Pull necessary docker images'
  task :pull => [:configure] do
    Gatekeeper::Runner.pull
  end

  desc 'Run screenshot tests on production with latest development version of showcar-ui'
  task :screenshot => [:configure] do
    ENV['SCREEN_HEIGHT'] = '5000'
    ENV['SPECTRE_PROJECT'] = 'Showcar'
    if ENV['GO_PIPELINE_COUNTER']
      ENV['SPECTRE_RUN_ID'] = "#{ENV['GO_PIPELINE_NAME']}-#{ENV['GO_PIPELINE_COUNTER']}"
    else
      ENV['SPECTRE_RUN_ID'] = "#{`hostname`.strip} - #{Time.now}"
    end
    specs = ["spec/layout"]
    Gatekeeper::Runner.run_in_container(*specs)
  end

  desc 'Run user journey tests on production with latest development version of showcar-ui'
  task :user_journeys => [:configure] do
    specs = [
      "spec/features/classified_detail",
      "spec/features/classified_list",
      "spec/features/home"
    ]
    Gatekeeper::Runner.run_in_container(*specs)
  end
end
